### ISSUE TITLE
Performance tracking issue

### ISSUE THREAD

**Issue by esjewett** [crossfilter/crossfilter#31]
Currently in the 2.0.0-alpha releases we have some performance regressions compared with the original Square repo. Reasons:

- [X] The move to support 32+ dimensions (#17 - in my original testing this was worth about a 5-10% performance hit on filtering, which we consider worthwhile for the functionality improvement and for the code-readability improvement). Therefore, no change is required here at the moment.
- [ ] The introduction of array support for dimensions. Because the array support code is all inline in the existing dimension and group code, it requires a fair number of switches. These are not a great code structure and also result in a real performance impact. I believe this accounts for most of the rest of the regression we are seeing in crossfilter2 right now (another 10-15% on top of 1 above).
- [ ] Un-optimized functions - currently, at least in V8, some the primitive functions that Crossfilter defines (quicksort, for example) are not optimized. This can be seen in the profiler. We should address this issue.
- [ ] Other?

Suggestions or contributions addressing these issues are welcome. Running `make benchmark` is the best way to test the performance impact on core operations.
 
<img width="592" alt="screen shot 2016-03-16 at 10 08 57 am" src="https://cloud.githubusercontent.com/assets/4822/13817180/3e12b8d8-eb5f-11e5-9287-fe290377c290.png">

**Comment by drarmstr** [comment]
If it's helpful, as a point of reference, I did some performance measurements compared to square/crossfilter with some of my workloads and was getting about a 25% performance regression.  I tested with both a smaller dataset with about 200k elements and a larger one with over 2 million.  I can perform more tests if helpful, but it seems like we have a significant amount.

**Comment by esjewett** [comment]
@drarmstr That aligns pretty well with what I am seeing from `make benchmark` as well. If you want to keep an eye on this issue, I'll update when there are changes.

Also, I just published version 1.3.13 in crossfilter2 on NPM, which doesn't have any of these changes so it should have performance basically identical to the current version the square repo. These bigger changes will be coming in version 1.4.0 and will be available for testing starting with 1.4.0-alpha.01, which won't install from NPM unless you explicitly specify that version.

**Comment by drarmstr** [comment]
One thought on improving the performance regression for 32+ dimensions would be that since the filter checking is now abstracted in `crossfilter_bitarray` is that two implementations could be provided.  One simpler one for <= 32 dimensions and this more complex one with subarrays for > 32 dimensions.  As the array is widened it would switch implementations over as it crosses the 32 threshold.  This way we could get the faster implementation unless we need support for > 32 dimensions.  It wouldn't be quite as fast as the original as there would still be an extra function call instead of just a map lookup, but it should help.  Thoughts?

**Comment by esjewett** [comment]
@drarmstr I really have very little intuition as to whether that would help or hurt :-) If you'd like to try it and report back, go for it! Personally, I suspect that the support for array dimension performance regression and the de-opt problems are bigger fish, but if you want to look at any of these problems we would be very grateful.

**Comment by drarmstr** [comment]
@esjewett Are you sure the de-opt is a regression?  I thought I saw that on the Square version as well.

Ok, I may experiment with this then.  But, I'm still on the Square version due to this regression and will probably wait until there is some compelling new feature to justify the investigative time of migrating.

Is someone planning to look at "array dimensions" performance?  I can also wait till after that is fixed to see if this is still a problem.  I'm actually not quite sure what "array dimensions" are yet..

**Comment by esjewett** [comment]
@drarmstr It is on the Square version as well. At some point Chrome either stopped optimizing the type of type conversions being done, or it never optimized them but started warning.

**Comment by esjewett** [comment]
@drarmstr Oh, I'm planning on looking at the array dimension performance, but I have little time until maybe summer :-( @tannerlinsley may be able to do something sooner, or I might be able to carve out some time, but we'll see. FWIW, our releases on the 1.3.* release don't have the new stuff, so they should have the same performance as the latest Square release.
